     name: ItemLock
     version: 0.3
     description: the plugin "locks" the items in place but allow them to be used. 
     author: fokolo     
     main: io.github.fokolo.lockitem
     
     commands:
       itemlock:
         description: itemlock root command.
         aliases: ilock
         usage: Syntax error! type /itemlock help.
