    name: LockItem
    main: io.github.fokolo.lockitem
    version: 0.3
    
    commands:
       unlock:
          description: Items will not lock on this player.
          usage: /unlock [player]
          permission: itemlock.unlock
          permission-message: You don't have permissions
    commands:
       lock:
          description: Items will lock on this player.
          usage: /lock [player]
          permission: itemlock.lock
          permission-message: You don't have permissions

    